Fix TypeError for missing `element.properties`
>> TypeError: Cannot read property 'length' of null
>>     at resources/jsdoc Export JSON/template/publish.js:96:118

Seems to be my fault.